# Numpy
NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices. 

NumPy stands for **Numerical Python**.

Q. Why Numpy? 

NumPy aims to provide an array object that is up to 50x faster than traditional Python lists. The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

Q. Why is NumPy Faster Than Lists?

NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

This behavior is called locality of reference in computer science.

This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.

In [4]:
# Installing 
!pip install numpy

In [1]:
# Importing Numpy
import numpy as np

In [3]:
# Checking the version 
print(np.__version__)

1.19.5


In [2]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


# Create
NumPy is used to work with arrays. The array object in NumPy is called ndarray. 

We can create a NumPy ndarray object by using the array() function.

In [5]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [6]:
arr = np.array((1, 2, 3, 4, 5))

print(arr)

[1 2 3 4 5]


In [11]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [28]:
# 1D Array
arr1 = np.array([1, 2, 3, 4, 5])

print(arr1)

[1 2 3 4 5]


In [29]:
# 2D Array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

print(arr2)

[[1 2 3]
 [4 5 6]]


In [31]:
# 3D Array
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr3)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [32]:
# Generating Array
data = np.random.rand(2,3,4)
zeroes = np.zeros((2,2,2))
full = np.full((2,2,2), 7)
ones = np.ones((2,2,2))

In [9]:
print('Random Array')
print(data)

print('Zeros Array')
print(zeroes)

print('Full Array')
print(full)

print('Ones Array')
print(ones)



Random Array
[[[0.93284618 0.27320099 0.7356872  0.10934151]
  [0.07222698 0.1620094  0.61063543 0.99422143]
  [0.02834517 0.36693749 0.14617868 0.20982417]]

 [[0.85308215 0.64961369 0.13580674 0.71686942]
  [0.62661828 0.44251617 0.67487661 0.97343963]
  [0.85939394 0.04599448 0.11307009 0.69808284]]]
Zeros Array
[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]
Full Array
[[[7 7]
  [7 7]]

 [[7 7]
  [7 7]]]
Ones Array
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


# Read

In [15]:
# Attributes

shape = data.shape
size = data.size
types= data.dtype

In [19]:
print('Shape: ')
print(shape)

print('Size: ')
print(size)

print('Types: ')
print(types)


Shape: 
(2, 3, 4)
Size: 
24
Types: 
float64


A dimension in arrays is one level of array depth (nested arrays).

In [22]:
# Slicing
arr = data[0]
slicer = data[0][0:2]
reverse = data[-1]
sing_level = data[0][0][0]

In [25]:
print(arr)
print('-----------')

print(slicer)
print('-----------')

print(reverse)
print('-----------')

print(sing_level)
print('-----------')


[[0.93284618 0.27320099 0.7356872  0.10934151]
 [0.07222698 0.1620094  0.61063543 0.99422143]
 [0.02834517 0.36693749 0.14617868 0.20982417]]
-----------
[[0.93284618 0.27320099 0.7356872  0.10934151]
 [0.07222698 0.1620094  0.61063543 0.99422143]]
-----------
[[0.85308215 0.64961369 0.13580674 0.71686942]
 [0.62661828 0.44251617 0.67487661 0.97343963]
 [0.85939394 0.04599448 0.11307009 0.69808284]]
-----------
0.9328461845424936
-----------


# Update

In [33]:
# Generating Array 
list1 = np.random.rand(10)
list2 = np.random.rand(10)

In [34]:
# Basic Maths 
add = np.add(list1, list2)
sub = np.subtract(list1, list2)
div = np.divide(list1, list2)
mult = np.multiply(list1, list2)
dot = np.dot(list1, list2)

In [36]:
# Results

print('Results')

print('Addition: ')
print(add)
print('--------------------------')


print('Subtraction: ')
print(sub)
print('--------------------------')

print('Division: ')
print(div)
print('--------------------------')

print('Multiplication: ')
print(mult)
print('--------------------------')

print('Dot Product: ')
print(dot)
print('--------------------------')

Results
Addition: 
[1.16532018 1.09498488 1.60139718 0.38308986 1.11006154 1.09224443
 0.91042348 1.29263342 1.56327359 0.77507398]
--------------------------
Subtraction: 
[ 0.19716816 -0.70728747  0.09030713  0.23953384 -0.3542279   0.11154986
  0.80120847 -0.16791362 -0.00988866  0.21315621]
--------------------------
Division: 
[ 1.40730827  0.21511589  1.11952581  4.33714812  0.51617776  1.22749153
 15.67213008  0.7700675   0.98742831  1.75867402]
--------------------------
Multiplication: 
[0.32977396 0.17468408 0.63907939 0.02234534 0.2766898  0.29513863
 0.04673398 0.41067655 0.61093163 0.13882603]
--------------------------
Dot Product: 
2.944879398372066
--------------------------


In [43]:
# Statistical Functions
sqrt = np.sqrt(25)
ab = np.abs(-2)
power = np.power(2,7)
log = np.log(25)
exp = np.exp([2,3])
mins = np.min(list1)
maxs = np.max(list1)

In [44]:
# Results

print('Results')

print('SQRT: ')
print(sqrt)
print('--------------------------')

print('ABS: ')
print(abs)
print('--------------------------')

print('Power: ')
print(power)
print('--------------------------')

print('Log: ')
print(log)
print('--------------------------')

print('Exp: ')
print(exp)
print('--------------------------')

print('Max and Min: ')
print(maxs)
print(mins)
print('--------------------------')


Results
SQRT: 
5.0
--------------------------
ABS: 
<built-in function abs>
--------------------------
Power: 
128
--------------------------
Log: 
3.2188758248682006
--------------------------
Exp: 
[ 7.3890561  20.08553692]
--------------------------
Max and Min: 
0.8558159742485384
0.19384870882488425
--------------------------


In [45]:
print(data)

[[[0.0760836  0.56793658 0.9820642  0.81920334]
  [0.80465965 0.01842755 0.59820601 0.84258687]
  [0.25693252 0.40756913 0.6936527  0.06583032]]

 [[0.20174536 0.04676    0.80562396 0.95305206]
  [0.49320101 0.83443923 0.57856639 0.6768167 ]
  [0.9005899  0.00621586 0.36591891 0.58019392]]]


In [46]:
data[0][0][0] = 7

In [47]:
print(data)

[[[7.00000000e+00 5.67936584e-01 9.82064200e-01 8.19203337e-01]
  [8.04659648e-01 1.84275480e-02 5.98206013e-01 8.42586866e-01]
  [2.56932523e-01 4.07569134e-01 6.93652700e-01 6.58303168e-02]]

 [[2.01745357e-01 4.67599955e-02 8.05623960e-01 9.53052061e-01]
  [4.93201008e-01 8.34439226e-01 5.78566389e-01 6.76816696e-01]
  [9.00589904e-01 6.21585859e-03 3.65918909e-01 5.80193923e-01]]]


In [48]:
# Sorting 
data.sort()

print(data)

[[[5.67936584e-01 8.19203337e-01 9.82064200e-01 7.00000000e+00]
  [1.84275480e-02 5.98206013e-01 8.04659648e-01 8.42586866e-01]
  [6.58303168e-02 2.56932523e-01 4.07569134e-01 6.93652700e-01]]

 [[4.67599955e-02 2.01745357e-01 8.05623960e-01 9.53052061e-01]
  [4.93201008e-01 5.78566389e-01 6.76816696e-01 8.34439226e-01]
  [6.21585859e-03 3.65918909e-01 5.80193923e-01 9.00589904e-01]]]


In [49]:
# Reshaping

print(data.shape)

data = data.reshape(2,2,-1)

print(data.shape)

(2, 3, 4)
(2, 2, 6)


In [51]:
# Adding

zeros = np.zeros(8)
print(zeros)

zeros = np.append(zeros, [1,2,3])
print(zeros)


[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 1. 2. 3.]


In [52]:
# Inserting at positon 2
zeros = np.insert(zeros, 2, 1) 
print(zeros)

[0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 2. 3.]


# Delete

In [53]:
print(data)

[[[5.67936584e-01 8.19203337e-01 9.82064200e-01 7.00000000e+00
   1.84275480e-02 5.98206013e-01]
  [8.04659648e-01 8.42586866e-01 6.58303168e-02 2.56932523e-01
   4.07569134e-01 6.93652700e-01]]

 [[4.67599955e-02 2.01745357e-01 8.05623960e-01 9.53052061e-01
   4.93201008e-01 5.78566389e-01]
  [6.76816696e-01 8.34439226e-01 6.21585859e-03 3.65918909e-01
   5.80193923e-01 9.00589904e-01]]]


In [55]:
np.delete(data, 0, axis=1)
print(data)

[[[5.67936584e-01 8.19203337e-01 9.82064200e-01 7.00000000e+00
   1.84275480e-02 5.98206013e-01]
  [8.04659648e-01 8.42586866e-01 6.58303168e-02 2.56932523e-01
   4.07569134e-01 6.93652700e-01]]

 [[4.67599955e-02 2.01745357e-01 8.05623960e-01 9.53052061e-01
   4.93201008e-01 5.78566389e-01]
  [6.76816696e-01 8.34439226e-01 6.21585859e-03 3.65918909e-01
   5.80193923e-01 9.00589904e-01]]]


# Saving and Loading

In [56]:
# Saving
np.save('my_data_array', data)

In [61]:
# Current Directory
import os
cwd = os.getcwd()

print(cwd)

/content


In [64]:
# Loading
my_data = np.load('/content/my_data_array.npy')

print(my_data)

[[[5.67936584e-01 8.19203337e-01 9.82064200e-01 7.00000000e+00
   1.84275480e-02 5.98206013e-01]
  [8.04659648e-01 8.42586866e-01 6.58303168e-02 2.56932523e-01
   4.07569134e-01 6.93652700e-01]]

 [[4.67599955e-02 2.01745357e-01 8.05623960e-01 9.53052061e-01
   4.93201008e-01 5.78566389e-01]
  [6.76816696e-01 8.34439226e-01 6.21585859e-03 3.65918909e-01
   5.80193923e-01 9.00589904e-01]]]
